// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "../schema.prisma",
  migrations: {
    path: "../migrations",
  },
  datasource: {
    url: "postgresql://postgres.smjlptzulfayjlyuowvq:@Tshegofatso16@aws-1-eu-west-1.pooler.supabase.com:5432/postgres"
  }
});
